### ISSUE TITLE
connection to Plotly-orca fail 

### ISSUE THREAD

**Issue by callumparr** [wdecoster/nanocomp#16]
Hi, not a big deal but the final step of creating static png images from the dynamic Plotly html files fails, and I know this is a known issue with orca. From the error message, I install Plotly-orca via conda but it still fails to find the excecutable. 

I am unsure how to implement this error message. I cannot find this config file. 

```
If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the plotly.io.orca.config.executable
property to the full path of your orca executable. For example:

>>> plotly.io.orca.config.executable = '/path/to/orca'
After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

>>> plotly.io.orca.config.save() 

```

**Comment by wdecoster** [comment]
Yeah, it seems tricky to have it properly installed. That's why I have it as an optional feature - if it fails the program should just carry on. It did not crash NanoComp, did it?

Based on the error message above you would have to execute that in a python interpreter. See also https://plot.ly/python/orca-management/ (from which you could also use code examples to test the configuraiton)

Something like 


```
import plotly.io as pio
pio.orca.config # see the current configuration settings
pio.orca.config.executable = '/path/to/orca'
pio.orca.config.save() 
```

Note that I didn't have to configure my system this way... Please let me know how it goes :-)

**Comment by callumparr** [comment]
Thanks! Yes it still saves the HTML files at the end, so it’s not an issue so much can just manually save an image. 

It just work straight away on my Mac. I will take a look later on Ubuntu. Thanks the compare identity from bam is nice feature.

**Comment by wdecoster** [comment]
Good to hear!
