### ISSUE TITLE
color control

### ISSUE THREAD

**Issue by devonorourke** [wdecoster/nanocomp#7]
Hi Wouter,

Is there a quick fix within the `NanoComp` package that could allow for a user to specify a color (or set of colors), just like in `NanoPlot`? I believe it's on line 177 of the `NanoPlot.py` script:  

```
visual.add_argument("-c", "--color",
                        help="Specify a color for the plots, must be a valid matplotlib color",
                        default="#4CB391")
```

The reason I ask is because it's nice to have that control when you're showing a series of individual figures generated within NanoPlot, then transition to the comparison with NanoComp. Ideally, the individual NanoPlot colors would match what is generated with NanoComp.  

Hope this is an easy one!

Thanks,

Devon

**Comment by wdecoster** [comment]
Indeed, those lines in NanoPlot define the `-- color` command line argument, of which the result gets then propagated to the individual plotting function in the nanoplotter submodule. For NanoPlot that's quite easy since there is only one color to be used. Since NanoComp uses multiple colors to distinguish the datasets I stuck to a default color scheme to make (my) life easier.

But as usual, it's definitely possible to add "color control" to NanoComp. I'll put it on the todolist!

Cheers,
Wouter

**Comment by wdecoster** [comment]
Upgrading to NanoComp 0.13.0 should add color control using the `-c/--color` argument. Thanks for the suggestion!
